name: Add a dataset
description: Add the description of a dataset.
title: "[Dataset Entry for the SwissAI Data Catalogue]: "
#labels: ["source-data-candidate"]
#projects: ["octo-org/1", "octo-org/44"]
#assignees:
#  - tbd
body:
  - type: markdown
    attributes:
      value: |
        Let's start with some generic information.
  - type: input
    id: uid
    attributes:
      label: UID of the record
      description: Please provide a short `snake_case` alias to your record.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Two-sentence description of the record
      description: Let us know briefly what is the dataset about.
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL where the dataset is published/available
    validations:
      required: true
  - type: input
    id: related_paper
    attributes:
      label: Related scientific paper (URL)
    validations:
      required: false
  - type: input
    id: datasheet
    attributes:
      label: Datasheet or dataset card (URL, if available)
    validations:
      required: false
  - type: input
    id: dataset_custodian
    attributes:
      label: Dataset custodian (email)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Information about the dataset itself
  - type: dropdown
    id: dataset_status
    attributes:
      label: Dataset processing status
      description: You can select multiple values from the dropdown
      multiple: true
      options: [ready-to-process, requires-copyright-clearance, requires-format-conversion, requires-quality-enhancement]
    validations:
      required: false



