name: Add a dataset
description: Add the description of a dataset.
title: "[Dataset Entry for the SwissAI Data Catalogue]: "
#labels: ["source-data-candidate"]
#projects: ["octo-org/1", "octo-org/44"]
#assignees:
#  - tbd
body:
  - type: markdown
      attributes:
        value: |
          Let's start with some generic information.
  - type: input
    id: uid
    attributes:
      label: UID of the record
      description: Please provide a short `snake_case` alias to your record.
      validations:
        required: true
  - type: input
    id: uid
    attributes:
      label: Two-sentence description of the record
      description: Let us know briefly what is the dataset about.
      validations:
        required: true
