name: Submit dataset record

on:
  issues:
    types: [labeled]

concurrency:
  group: dataset-submission-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  submit_dataset:
    if: ${{ github.event.label.name == 'dataset_candidate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create dataset directory
        run: mkdir -p datasets

      - name: Parse issue content
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/dataset_template.yml

      - name: Save dataset record
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > datasets/${{ steps.issue-parser.outputs.issueparser_uid }}.json

      - name: Configure Git
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add datasets/${{ steps.issue-parser.outputs.issueparser_uid }}.json
          git commit -m "Add new dataset record for issue #${{ github.event.issue.number }}"
          git push || echo "No changes to commit or push"

      - name: Comment on Issue
        if: ${{ always() }}
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = ${{ github.event.issue.number }};
            const message = `Your dataset submission has been processed. Please check the datasets folder for the record.`;
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
